package com.turlygazhy.entity;

/**
 * Created by user on 1/17/17.
 */
public enum WaitingType {
    NISHA, CONTACT, PLAN_NAME, PLAN_GOAL, READED_COUNT, GROUP_ID, GOAL_NAME, GOAL_DIGIT, AVAILABLE_TIME_START, AVAILABLE_TIME_END, CHANGE_GOAL, GOAL_COMPLETED, BOOK_NAME, CHECK_BOOK_NAME, NEW_THESIS, CHANGE_THESIS, CHANGE_PAGE, PERIOD, PERIOD_START, PERIOD_END, CHOOSE_GOAL, CHANGE_TYPE, GOAL_NEW_NAME, PHOTO, TEXT, NAME, BIRTHDAY, SEX, CITY, PHONE_NUMBER, COMMAND, CHOOSE_TASK_TYPE, CHOOSE_TASK, TASK_COMMAND, NAME_FOR_ADMIN, DESCRIPTION, TYPE_OF_WORK, DATE, CHOOSE_STOCK, CHOOSE_TYPE_OF_WORK, CHOOSE_DATE, FOR_WHOM, MESSAGE, CHOOSE, CHOOSE_STOCK_TYPE, CHOOSE_NEWS, URL, COUNT, CAR_LIST, FAMILY_LIST, CHOOSE_FAMILY, CHOOSE_ADMIN, CHOOSE_SUPER_ADMIN, REPORT, YEAR, MONTH, DAY, CHOOSE_USERS, CHOOSE_LIST, CHOOSE_TYPE, CHOOSE_STOCK_TEMPLATE, CHOOSE_STOCK_TEMPLATE_TYPE, CHOOSE_PARAMETR, CHOOSE_ANSWER, CHOOSE_REPORT_ANSWER, CHOOSE_DECILINE_ANSWER, CHOOSE_GROUP, CHOOSE_EDIT_STOCK, CHOOSE_EDIT_TASK, CHOOSE_TASK_PARAMETR, NEW_DATE, CHOOSE_DATE_COMMAND, CHOOSE_DATE_CHANGE, NEW_TASK, NAVIKI
}
